language: java
sudo: true # faster builds
jdk: oraclejdk1.8
install: mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true
services:
  - mysql
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client
before_install:
  - chmod +x mvnw
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('root') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade -uroot -proot
  - sudo service mysql restart
  - sudo mysql -uroot -proot -e 'CREATE DATABASE IF NOT EXISTS spiny;'
